// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Record

package main

// RecordSlice is a slice of type Record. Use it where you would use []Record.
type RecordSlice []Record

// Where returns a new RecordSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv RecordSlice) Where(fn func(Record) bool) (result RecordSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
